# Generated by Django 2.2 on 2019-05-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0003_auto_20190508_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='author',
            field=models.CharField(default=-1.0, max_length=30),
            preserve_default=False,
        ),
    ]
