# Generated by Django 2.2 on 2019-05-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_blogs_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog',
            field=models.CharField(max_length=300),
        ),
    ]
